sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

php:
  - 5.5
  - 5.6
  - 7.0

cache:
  - composer
  - $HOME/.composer/cache

before_script: composer setup
script: vendor/bin/behat
